---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: my-app
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app  #should match with template.metadata.labels
  template:
    metadata:
      labels:
        app: my-app   # Should match with selector.matchLabels
    spec:
      containers:
        - name: app
          #image: docker.io/library/app:1.2 Local image
          #image: adithyasv/my-app:1.3 # Docker Hub image
          image: kafkastudyacr.azurecr.io/myapp:latest # Private ACR image
          imagePullPolicy: Always #Always / IfNotPresent / Never
          ports:
            - containerPort: 8080
              protocol: TCP
